div:type=(titlepage|dedication|poempart|song|colophon)
head:type=(title|subtitle|parthead),-=*
lg:
p:
trailer:
fw:
q:
l:rend=(indent1|indent2|indent3|indent4|indent5),part=F,-=*
hi:rend=(ul|sc|b|it|dul|ss|erasure|bl|pencil|del-pencil)
emph:
unclear:
expan:
metamark:target=*,-=*
author:
date:
sic:
pb:facs=*,n=*
note:name=*,resp=(Harpur|MJS|DS|Sydney Journal|Anonymous)
body:
add:
del:
TEI:
graphic:url=*
divider:type=(diamond|single|double)
text:
app:
rdg:
ref:target=*
